val is_hidden : string -> bool
(** [is_hidden s] returns whether [s] is the name of a hidden module, ie. if it
    is generated by [odoc] and contains "__". *)

val lines_of_channel : in_channel -> string list
(** [lines_of_channel c] returns lines read on channel [c]. *)

val lines_of_process : Bos.Cmd.t -> string list
(** [lines_of_process p] returns lines read from the output of process [p]. *)

val run_silent : Bos.Cmd.t -> unit
(** [run_silent c] runs command [c] without displaying the output. *)

val mkdir_p : Fpath.t -> unit
(** [mkdir_p x] recursively creates directory [x] and its parents. *)

val copy : Fpath.t -> Fpath.t -> (unit, [> Bos_setup.R.msg ]) Bos_setup.result
(** [copy src dst] copies [src] to [dst]. *)
